print ('olá esse é seu primeiro programa em python')
print ('informe seu nome')
nome = input()
print ('é bom te ver por aqui, ' + nome)
print ('o tamanho do seu nome é de: ' )
print (len(nome))
print ('qual a sua idade?')
idade = input()
print ('voce terá ' + str(int(idade) + 1) + 'em 1 ano.')
